# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-
require './lib/graphy/version'

Gem::Specification.new do |s|
  s.name = %q{graphy}
  s.version = Graphy::VERSION
  s.authors = ["Bruce Williams", "Jean-Denis Vauguet <jd@vauguet.fr>"]
  s.summary = "A framework for graph data structures and algorithms."
  s.description = %q{This library is based on GRATR and RGL.

Graph algorithms currently provided are:

* Topological Sort
* Strongly Connected Components
* Transitive Closure
* Rural Chinese Postman
* Biconnected
}
  s.email = %q{bruce@codefluency.com}
  s.add_dependency "facets"
  s.add_development_dependency "rspec"
  s.add_development_dependency "yard"
end

